### ISSUE TITLE
Update text log to proper geometric notation

### ISSUE THREAD

**Issue by uscdrew** [SCCapstone/490Euclidean#33]
Examples provided by the client: 
https://drive.google.com/file/d/1800F_tzquzoJsds3nA-rndcTnJ0yZ2gI/view?usp=sharing

https://drive.google.com/file/d/1Qb8XnBqJX5Is5WUGU7YNajjIlLxLoS6I/view?usp=sharing

**Comment by khoraski** [comment]
The notation matches the documents. If there are any specific issues in the notation that come up later, feel free to open a separate issue.
