### ISSUE TITLE
Do not use alert()

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/490Euclidean#40]
![demo html name mylab data d0 253a 2520t 250a action save status success 2019-03-05 06-23-01](https://user-images.githubusercontent.com/228704/53802209-423f1300-3f0f-11e9-9240-e7c1dc30c481.jpg)

**Comment by khoraski** [comment]
All alerts were removed from the code.

**Comment by josemvidal** [comment]
When you close an issue by writing code, either fixing a bug or creating a new feature, you should add a link to the git-commit(s) that did it.

This can be done automatically if you just write "closes #X" in the comment of the git-commit, where X is the issue number you want to close. See [closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/) for more information.
