### ISSUE TITLE
Fix drawing UI for Lines, Circles

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/490Euclidean#41]
The way the user must place lines and circles is non-intuitive. Fix it.

You can put up guidance instructions: "now click on the center of the circle" as the user clicks on the buttons.

The UI should clearly show when we are in "line drawing mode". Typically, paint programs show you the tool you are currently using in the cursor: pencil, pen, paint bucket..., for you it would be Point, Line, Circle,... Or, you can disable/gray-out the other choices while the user is using one of them.

![screencast 2019-03-05 06-25-37](https://user-images.githubusercontent.com/228704/53802636-53d4ea80-3f10-11e9-8cb4-75ba64f96dd9.gif)

**Comment by khoraski** [comment]
Several changes have been made to the UI to make it more intuitive plus a Help page to explain things. It should be fairly easy to use at this point. For now I will close this issue since we do not plan to make anymore major changes.
