### ISSUE TITLE
Show project title while working on project, and remove "Project Name" box

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/490Euclidean#42]
![demo html name deelab data d0 253a 2520t 250ad1 253a 2520 2524p1 2520 253d 2520a 250ad2 253a 2520 2524p2 2 2019-03-05 06-34-57](https://user-images.githubusercontent.com/228704/53802915-1de43600-3f11-11e9-8b3c-42845b4d9319.jpg)

**Comment by khoraski** [comment]
Implemented.

**Comment by josemvidal** [comment]
When you close an issue by writing code, either fixing a bug or creating a new feature, you should add a link to the git-commit(s) that did it.

This can be done automatically if you just write "closes #X" in the comment of the git-commit, where X is the issue number you want to close. See [closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/) for more information.
