### ISSUE TITLE
Editing text messes up proof

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/490Euclidean#43]
If a have 

```
d0: T
d1: $p1 = A
d2: $p2 = B
d3: $p3 = C
d4: $s1(p2,p3) = a
```

then delete 

```
d1: $p1 = A
```

the line p2--p3 dissapears:

![screencast 2019-03-05 06-42-28](https://user-images.githubusercontent.com/228704/53803271-3274fe00-3f12-11e9-8587-0c0cddf660a6.gif)

**Comment by khoraski** [comment]
Should be fixed now. There were two separate bugs here. One had to do with points not being remapped properly and the other had to do with press enter inserting new lines where it shouldn't and so it'd glitch out when trying to parse it.
