### ISSUE TITLE
Help page is 404

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/490Euclidean#44]
![screencast 2019-03-05 06-53-51](https://user-images.githubusercontent.com/228704/53803702-816f6300-3f13-11e9-80df-f05daa1da7f3.gif)

**Comment by hman151** [comment]
sorry about that, Help linked directly to our README on github, but we made our repository private meaning you couldn't view it, I just made it public so you can view it

**Comment by mzdu** [comment]
Why don't we create a separate HTML page instead of using the github repo? It should provide some basic instructions on how to use your app, common questions and answers. The github page is more for developers.

**Comment by hman151** [comment]
we are currently working on that

**Comment by josemvidal** [comment]
Yes, the help page is part of your app. It should reside on the same host.
