### ISSUE TITLE
Explain what symbols mean

### ISSUE THREAD

**Issue by KingLuvely** [SCCapstone/490Euclidean#52]
Adding a way to explain what the symbols mean would be helpful for UX. 
![qa symbols](https://user-images.githubusercontent.com/8549247/55754962-d2dfa600-5a1b-11e9-93ca-cbbc854f56b0.PNG)

**Comment by khoraski** [comment]
How did you do this? I can't seem to replicate this. It is coded with a hard limit of 26 points. So I'm not sure how you accomplished this.

**Comment by KingLuvely** [comment]
It did stop after 26 points but if you save it, load it back in, and do other functions (like circle or adding a line) and then click random point more, they come up.
